### PR TITLE
Update fvm to 1.3.8

### PR DESCRIPTION
**Pull request by benedictkhoo**

### CODE REVIEW

**Comment by leoafarias** [comment]
@benedictkhoo thank you for the PR, however, this is automated by the release process on FVM which seemed to have failed. I will go ahead and review, what happened.

**Comment by leoafarias** [comment]
@benedictkhoo the issue has been corrected, and the update is now live.

**Comment by benedictkhoo** [comment]
Awesome! Thanks @leoafarias ! 👍

**Comment by benedictkhoo** [comment]
@leoafarias as a side note, the current URL pointing to 1.3.1 returns a 404. Is it possible to update it to the latest stable release?

**Comment by leoafarias** [comment]
@benedictkhoo I didnt have the tooling setup, on that version and was testing. Can you do a PR for version 1.3.8, that should be the latest one

**Pull request merged**
